### ISSUE TITLE
Permissions Handler is faulty

### ISSUE THREAD

**Issue by josiiah** [AmethystFramework/framework#6]
If you don't have the required permissions it's supposed to send a message in the channel, message the user or return null. This doesn't seem to work with the framework properly yet! 

It instead returns:

```
{"message":"Missing Permissions","code":50013}
error: Uncaught (in promise) Error: [403] The Authorization token you passed did not have permission to the resource.
  Error.captureStackTrace(errorStack);
```

**Comment by some-boi** [comment]
it was the bot not having permissions for a function inside the execute method
